// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'6b0ddccfad6a63788f6799d5a342f56ae48d7f586f15da62238c3d867a5960e8'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly ComplaintEmployees: {
      readonly complaintId: CodecTypes['pg/int4@1']['output'];
      readonly employeeId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Complaints: {
      readonly complaintDetail: CodecTypes['pg/text@1']['output'];
      readonly complaintId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly customerId: CodecTypes['pg/int4@1']['output'];
      readonly status: Varchar<20>;
      readonly typeId: CodecTypes['pg/int4@1']['output'];
    };
    readonly ComplaintTypes: {
      readonly name: Varchar<100>;
      readonly typeId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Customers: {
      readonly contact: Varchar<100>;
      readonly customerId: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
      readonly userId: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly Employees: {
      readonly employeeId: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
      readonly phone: Varchar<20>;
      readonly title: Varchar<100>;
      readonly userId: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly Messages: {
      readonly complaintId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly customerId: CodecTypes['pg/int4@1']['output'] | null;
      readonly employeeId: CodecTypes['pg/int4@1']['output'] | null;
      readonly messageId: CodecTypes['pg/int4@1']['output'];
      readonly messageText: CodecTypes['pg/text@1']['output'];
    };
    readonly Users: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly email: Varchar<150>;
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly role: Varchar<20>;
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly ComplaintEmployees: {
      readonly complaintId: CodecTypes['pg/int4@1']['input'];
      readonly employeeId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Complaints: {
      readonly complaintDetail: CodecTypes['pg/text@1']['input'];
      readonly complaintId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly customerId: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['sql/varchar@1']['input'];
      readonly typeId: CodecTypes['pg/int4@1']['input'];
    };
    readonly ComplaintTypes: {
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly typeId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Customers: {
      readonly contact: CodecTypes['sql/varchar@1']['input'];
      readonly customerId: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly Employees: {
      readonly employeeId: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly phone: CodecTypes['sql/varchar@1']['input'];
      readonly title: CodecTypes['sql/varchar@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly Messages: {
      readonly complaintId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly customerId: CodecTypes['pg/int4@1']['input'] | null;
      readonly employeeId: CodecTypes['pg/int4@1']['input'] | null;
      readonly messageId: CodecTypes['pg/int4@1']['input'];
      readonly messageText: CodecTypes['pg/text@1']['input'];
    };
    readonly Users: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly role: CodecTypes['sql/varchar@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly complaint_employees: {
      readonly complaint_id: CodecTypes['pg/int4@1']['output'];
      readonly employee_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly complaint_types: {
      readonly name: Varchar<100>;
      readonly type_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly complaints: {
      readonly complaint_detail: CodecTypes['pg/text@1']['output'];
      readonly complaint_id: CodecTypes['pg/int4@1']['output'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly customer_id: CodecTypes['pg/int4@1']['output'];
      readonly status: Varchar<20>;
      readonly type_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly customers: {
      readonly contact: Varchar<100>;
      readonly customer_id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
      readonly user_id: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly employees: {
      readonly employee_id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
      readonly phone: Varchar<20>;
      readonly title: Varchar<100>;
      readonly user_id: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly messages: {
      readonly complaint_id: CodecTypes['pg/int4@1']['output'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly customer_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly employee_id: CodecTypes['pg/int4@1']['output'] | null;
      readonly message_id: CodecTypes['pg/int4@1']['output'];
      readonly message_text: CodecTypes['pg/text@1']['output'];
    };
    readonly users: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly email: Varchar<150>;
      readonly password_hash: CodecTypes['pg/text@1']['output'];
      readonly role: Varchar<20>;
      readonly user_id: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly complaint_employees: {
      readonly complaint_id: CodecTypes['pg/int4@1']['input'];
      readonly employee_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly complaint_types: {
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly type_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly complaints: {
      readonly complaint_detail: CodecTypes['pg/text@1']['input'];
      readonly complaint_id: CodecTypes['pg/int4@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly customer_id: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['sql/varchar@1']['input'];
      readonly type_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly customers: {
      readonly contact: CodecTypes['sql/varchar@1']['input'];
      readonly customer_id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly employees: {
      readonly employee_id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly phone: CodecTypes['sql/varchar@1']['input'];
      readonly title: CodecTypes['sql/varchar@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly messages: {
      readonly complaint_id: CodecTypes['pg/int4@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly customer_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly employee_id: CodecTypes['pg/int4@1']['input'] | null;
      readonly message_id: CodecTypes['pg/int4@1']['input'];
      readonly message_text: CodecTypes['pg/text@1']['input'];
    };
    readonly users: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly password_hash: CodecTypes['pg/text@1']['input'];
      readonly role: CodecTypes['sql/varchar@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
    };
  };
};

export namespace Models {
  export type public_ComplaintEmployees = {
    complaintId: CodecTypes['pg/int4@1']['output'];
    employeeId: CodecTypes['pg/int4@1']['output'];
    complaint: public_Complaints;
    employee: public_Employees;
    readonly [RelationKeys]?: 'complaint' | 'employee';
  };
  export type public_ComplaintTypes = {
    name: Varchar<100>;
    typeId: CodecTypes['pg/int4@1']['output'];
    complaints: public_Complaints[];
    readonly [RelationKeys]?: 'complaints';
  };
  export type public_Complaints = {
    complaintDetail: CodecTypes['pg/text@1']['output'];
    complaintId: CodecTypes['pg/int4@1']['output'];
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    customerId: CodecTypes['pg/int4@1']['output'];
    status: Varchar<20>;
    typeId: CodecTypes['pg/int4@1']['output'];
    _type: public_ComplaintTypes;
    complaintEmployees: public_ComplaintEmployees[];
    customer: public_Customers;
    messages: public_Messages[];
    readonly [RelationKeys]?: '_type' | 'complaintEmployees' | 'customer' | 'messages';
  };
  export type public_Customers = {
    contact: Varchar<100>;
    customerId: CodecTypes['pg/int4@1']['output'];
    name: Varchar<100>;
    userId: CodecTypes['pg/int4@1']['output'] | null;
    complaints: public_Complaints[];
    messages: public_Messages[];
    user: public_Users | null;
    readonly [RelationKeys]?: 'complaints' | 'messages' | 'user';
  };
  export type public_Employees = {
    employeeId: CodecTypes['pg/int4@1']['output'];
    name: Varchar<100>;
    phone: Varchar<20>;
    title: Varchar<100>;
    userId: CodecTypes['pg/int4@1']['output'] | null;
    complaintEmployees: public_ComplaintEmployees[];
    messages: public_Messages[];
    user: public_Users | null;
    readonly [RelationKeys]?: 'complaintEmployees' | 'messages' | 'user';
  };
  export type public_Messages = {
    complaintId: CodecTypes['pg/int4@1']['output'];
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    customerId: CodecTypes['pg/int4@1']['output'] | null;
    employeeId: CodecTypes['pg/int4@1']['output'] | null;
    messageId: CodecTypes['pg/int4@1']['output'];
    messageText: CodecTypes['pg/text@1']['output'];
    complaint: public_Complaints;
    customer: public_Customers | null;
    employee: public_Employees | null;
    readonly [RelationKeys]?: 'complaint' | 'customer' | 'employee';
  };
  export type public_Users = {
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    email: Varchar<150>;
    passwordHash: CodecTypes['pg/text@1']['output'];
    role: Varchar<20>;
    userId: CodecTypes['pg/int4@1']['output'];
    customers: public_Customers | null;
    employees: public_Employees | null;
    readonly [RelationKeys]?: 'customers' | 'employees';
  };
}

export declare const models: {
  public: {
    ComplaintEmployees: Models.public_ComplaintEmployees;
    ComplaintTypes: Models.public_ComplaintTypes;
    Complaints: Models.public_Complaints;
    Customers: Models.public_Customers;
    Employees: Models.public_Employees;
    Messages: Models.public_Messages;
    Users: Models.public_Users;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly complaint_employees: {
              columns: {
                readonly complaint_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly employee_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['complaint_id', 'employee_id'];
                readonly name: 'complaint_employees_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'complaint_employees';
                    readonly columns: readonly ['complaint_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'complaints';
                    readonly columns: readonly ['complaint_id'];
                  };
                  readonly name: 'complaint_employees_complaint_id_fkey';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'complaint_employees';
                    readonly columns: readonly ['employee_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'employees';
                    readonly columns: readonly ['employee_id'];
                  };
                  readonly name: 'complaint_employees_employee_id_fkey';
                },
              ];
            };
            readonly complaint_types: {
              columns: {
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly type_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
              };
              primaryKey: {
                readonly columns: readonly ['type_id'];
                readonly name: 'complaint_types_pkey';
              };
              uniques: readonly [
                { readonly columns: readonly ['name']; readonly name: 'complaint_types_name_key' },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly complaints: {
              columns: {
                readonly complaint_detail: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly complaint_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly customer_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sql/varchar@1', 'OPEN'>;
                  };
                  readonly typeParams: { readonly length: 20 };
                };
                readonly type_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['complaint_id'];
                readonly name: 'complaints_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'complaints';
                    readonly columns: readonly ['customer_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'customers';
                    readonly columns: readonly ['customer_id'];
                  };
                  readonly name: 'fk_complaint_customer';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'complaints';
                    readonly columns: readonly ['type_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'complaint_types';
                    readonly columns: readonly ['type_id'];
                  };
                  readonly name: 'fk_complaint_type';
                },
              ];
            };
            readonly customers: {
              columns: {
                readonly contact: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly customer_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: {
                readonly columns: readonly ['customer_id'];
                readonly name: 'customers_pkey';
              };
              uniques: readonly [
                { readonly columns: readonly ['user_id']; readonly name: 'customers_user_id_key' },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'customers';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly name: 'fk_customer_user';
                },
              ];
            };
            readonly employees: {
              columns: {
                readonly employee_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly phone: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 20 };
                };
                readonly title: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: {
                readonly columns: readonly ['employee_id'];
                readonly name: 'employees_pkey';
              };
              uniques: readonly [
                { readonly columns: readonly ['user_id']; readonly name: 'employees_user_id_key' },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'employees';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly name: 'fk_employee_user';
                },
              ];
            };
            readonly messages: {
              columns: {
                readonly complaint_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly customer_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly employee_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly message_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly message_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['message_id'];
                readonly name: 'messages_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'messages';
                    readonly columns: readonly ['complaint_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'complaints';
                    readonly columns: readonly ['complaint_id'];
                  };
                  readonly name: 'fk_message_complaint';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'messages';
                    readonly columns: readonly ['customer_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'customers';
                    readonly columns: readonly ['customer_id'];
                  };
                  readonly name: 'fk_message_customer';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'messages';
                    readonly columns: readonly ['employee_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'employees';
                    readonly columns: readonly ['employee_id'];
                  };
                  readonly name: 'fk_message_employee';
                },
              ];
            };
            readonly users: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 150 };
                };
                readonly password_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sql/varchar@1', 'CUSTOMER'>;
                  };
                  readonly typeParams: { readonly length: 20 };
                };
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['user_id']; readonly name: 'users_pkey' };
              uniques: readonly [
                { readonly columns: readonly ['email']; readonly name: 'users_email_key' },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly complaint_employees: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ComplaintEmployees';
    };
    readonly complaint_types: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ComplaintTypes';
    };
    readonly complaints: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Complaints';
    };
    readonly customers: { readonly namespace: 'public' & NamespaceId; readonly model: 'Customers' };
    readonly employees: { readonly namespace: 'public' & NamespaceId; readonly model: 'Employees' };
    readonly messages: { readonly namespace: 'public' & NamespaceId; readonly model: 'Messages' };
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'Users' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly ComplaintEmployees: {
            readonly fields: {
              readonly complaintId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly employeeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly complaint: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Complaints';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['complaintId'];
                  readonly targetFields: readonly ['complaintId'];
                };
              };
              readonly employee: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Employees';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['employeeId'];
                  readonly targetFields: readonly ['employeeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'complaint_employees';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly complaintId: { readonly column: 'complaint_id' };
                readonly employeeId: { readonly column: 'employee_id' };
              };
            };
          };
          readonly Complaints: {
            readonly fields: {
              readonly complaintDetail: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly complaintId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
              readonly customerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
              readonly typeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly _type: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ComplaintTypes';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['typeId'];
                  readonly targetFields: readonly ['typeId'];
                };
              };
              readonly complaintEmployees: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ComplaintEmployees';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['complaintId'];
                  readonly targetFields: readonly ['complaintId'];
                };
              };
              readonly customer: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Customers';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['customerId'];
                  readonly targetFields: readonly ['customerId'];
                };
              };
              readonly messages: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Messages';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['complaintId'];
                  readonly targetFields: readonly ['complaintId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'complaints';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly complaintDetail: { readonly column: 'complaint_detail' };
                readonly complaintId: { readonly column: 'complaint_id' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly customerId: { readonly column: 'customer_id' };
                readonly status: { readonly column: 'status' };
                readonly typeId: { readonly column: 'type_id' };
              };
            };
          };
          readonly ComplaintTypes: {
            readonly fields: {
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly typeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly complaints: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Complaints';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['typeId'];
                  readonly targetFields: readonly ['typeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'complaint_types';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly name: { readonly column: 'name' };
                readonly typeId: { readonly column: 'type_id' };
              };
            };
          };
          readonly Customers: {
            readonly fields: {
              readonly contact: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly customerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly userId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly complaints: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Complaints';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['customerId'];
                  readonly targetFields: readonly ['customerId'];
                };
              };
              readonly messages: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Messages';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['customerId'];
                  readonly targetFields: readonly ['customerId'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'customers';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly contact: { readonly column: 'contact' };
                readonly customerId: { readonly column: 'customer_id' };
                readonly name: { readonly column: 'name' };
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
          readonly Employees: {
            readonly fields: {
              readonly employeeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly phone: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly userId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly complaintEmployees: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ComplaintEmployees';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['employeeId'];
                  readonly targetFields: readonly ['employeeId'];
                };
              };
              readonly messages: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Messages';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['employeeId'];
                  readonly targetFields: readonly ['employeeId'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'employees';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly employeeId: { readonly column: 'employee_id' };
                readonly name: { readonly column: 'name' };
                readonly phone: { readonly column: 'phone' };
                readonly title: { readonly column: 'title' };
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
          readonly Messages: {
            readonly fields: {
              readonly complaintId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
              readonly customerId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly employeeId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly messageId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly messageText: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly complaint: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Complaints';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['complaintId'];
                  readonly targetFields: readonly ['complaintId'];
                };
              };
              readonly customer: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Customers';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['customerId'];
                  readonly targetFields: readonly ['customerId'];
                };
              };
              readonly employee: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Employees';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['employeeId'];
                  readonly targetFields: readonly ['employeeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'messages';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly complaintId: { readonly column: 'complaint_id' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly customerId: { readonly column: 'customer_id' };
                readonly employeeId: { readonly column: 'employee_id' };
                readonly messageId: { readonly column: 'message_id' };
                readonly messageText: { readonly column: 'message_text' };
              };
            };
          };
          readonly Users: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 150 };
                };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly customers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Customers';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly employees: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Employees';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly email: { readonly column: 'email' };
                readonly passwordHash: { readonly column: 'password_hash' };
                readonly role: { readonly column: 'role' };
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
